---
name: Run Daily Go Script

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run Go Script
        run: go run main.go
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
